//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSE445_A9A10.AccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IControl")]
    public interface IControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/ValidateStaff", ReplyAction="http://tempuri.org/IControl/ValidateStaffResponse")]
        bool ValidateStaff(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/ValidateStaff", ReplyAction="http://tempuri.org/IControl/ValidateStaffResponse")]
        System.Threading.Tasks.Task<bool> ValidateStaffAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/ValidateUser", ReplyAction="http://tempuri.org/IControl/ValidateUserResponse")]
        bool ValidateUser(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/ValidateUser", ReplyAction="http://tempuri.org/IControl/ValidateUserResponse")]
        System.Threading.Tasks.Task<bool> ValidateUserAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/CreateUser", ReplyAction="http://tempuri.org/IControl/CreateUserResponse")]
        bool CreateUser(string first, string last, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/CreateUser", ReplyAction="http://tempuri.org/IControl/CreateUserResponse")]
        System.Threading.Tasks.Task<bool> CreateUserAsync(string first, string last, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/RemoveUser", ReplyAction="http://tempuri.org/IControl/RemoveUserResponse")]
        bool RemoveUser(string first, string last);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/RemoveUser", ReplyAction="http://tempuri.org/IControl/RemoveUserResponse")]
        System.Threading.Tasks.Task<bool> RemoveUserAsync(string first, string last);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/ListMembers", ReplyAction="http://tempuri.org/IControl/ListMembersResponse")]
        string[] ListMembers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControl/ListMembers", ReplyAction="http://tempuri.org/IControl/ListMembersResponse")]
        System.Threading.Tasks.Task<string[]> ListMembersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlChannel : CSE445_A9A10.AccountService.IControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlClient : System.ServiceModel.ClientBase<CSE445_A9A10.AccountService.IControl>, CSE445_A9A10.AccountService.IControl {
        
        public ControlClient() {
        }
        
        public ControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateStaff(string user, string pass) {
            return base.Channel.ValidateStaff(user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateStaffAsync(string user, string pass) {
            return base.Channel.ValidateStaffAsync(user, pass);
        }
        
        public bool ValidateUser(string user, string pass) {
            return base.Channel.ValidateUser(user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateUserAsync(string user, string pass) {
            return base.Channel.ValidateUserAsync(user, pass);
        }
        
        public bool CreateUser(string first, string last, string user, string pass) {
            return base.Channel.CreateUser(first, last, user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> CreateUserAsync(string first, string last, string user, string pass) {
            return base.Channel.CreateUserAsync(first, last, user, pass);
        }
        
        public bool RemoveUser(string first, string last) {
            return base.Channel.RemoveUser(first, last);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveUserAsync(string first, string last) {
            return base.Channel.RemoveUserAsync(first, last);
        }
        
        public string[] ListMembers() {
            return base.Channel.ListMembers();
        }
        
        public System.Threading.Tasks.Task<string[]> ListMembersAsync() {
            return base.Channel.ListMembersAsync();
        }
    }
}
